# Generated by Django 4.2.4 on 2023-08-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shopcls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('type_shop', models.CharField(max_length=40)),
                ('picture', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=14)),
                ('description', models.TextField()),
            ],
        ),
    ]
