# Generated by Django 4.2.4 on 2023-08-21 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcls',
            old_name='address',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='shopcls',
            old_name='description',
            new_name='description2',
        ),
        migrations.RenameField(
            model_name='shopcls',
            old_name='name',
            new_name='name2',
        ),
        migrations.RenameField(
            model_name='shopcls',
            old_name='phone',
            new_name='phone2',
        ),
        migrations.RenameField(
            model_name='shopcls',
            old_name='picture',
            new_name='picture2',
        ),
        migrations.RenameField(
            model_name='shopcls',
            old_name='type_shop',
            new_name='type_shop2',
        ),
    ]
