# Generated by Django 4.2.4 on 2023-08-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0002_rename_address_shopcls_address2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shopcls',
            new_name='shopcls2',
        ),
    ]
