# Generated by Django 4.2.4 on 2023-08-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0003_rename_shopcls_shopcls2'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopcls1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=300)),
                ('type_shop1', models.CharField(max_length=50)),
                ('picture1', models.CharField(max_length=50)),
                ('phone1', models.CharField(max_length=20)),
                ('description1', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='shopcls2',
            name='address2',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='shopcls2',
            name='phone2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shopcls2',
            name='picture2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shopcls2',
            name='type_shop2',
            field=models.CharField(max_length=50),
        ),
    ]
