# Generated by Django 4.2.4 on 2023-08-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0004_shopcls1_alter_shopcls2_address2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcls1',
            name='phase',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shopcls2',
            name='phase2',
            field=models.IntegerField(default=2),
        ),
    ]
