# Generated by Django 4.2.4 on 2023-08-22 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0005_shopcls1_phase_shopcls2_phase2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcls1',
            old_name='phase',
            new_name='phase1',
        ),
    ]
