# Generated by Django 4.2.4 on 2023-08-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0006_rename_phase_shopcls1_phase1'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactcls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
