# Generated by Django 4.2.4 on 2023-08-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0009_blogcls_officecls'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicescls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serv_name', models.CharField(max_length=50)),
                ('serv_pic', models.CharField(max_length=50)),
                ('serv_dec', models.CharField(max_length=2000)),
            ],
        ),
    ]
