# Generated by Django 4.2.4 on 2023-08-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0010_servicescls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcls',
            old_name='blog_dic',
            new_name='blog_desc',
        ),
        migrations.RenameField(
            model_name='servicescls',
            old_name='serv_dec',
            new_name='serv_desc',
        ),
    ]
