# Generated by Django 4.2.4 on 2023-08-26 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0011_rename_blog_dic_blogcls_blog_desc_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shopcls2',
            new_name='shopcls',
        ),
        migrations.DeleteModel(
            name='shopcls1',
        ),
        migrations.RenameField(
            model_name='shopcls',
            old_name='address2',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='shopcls',
            old_name='description2',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='shopcls',
            old_name='name2',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='shopcls',
            old_name='phase2',
            new_name='phase',
        ),
        migrations.RenameField(
            model_name='shopcls',
            old_name='phone2',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='shopcls',
            old_name='picture2',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='shopcls',
            old_name='type_shop2',
            new_name='type_shop',
        ),
    ]
