# Generated by Django 4.2.4 on 2023-08-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0012_rename_shopcls2_shopcls_delete_shopcls1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcls',
            name='icone',
            field=models.CharField(default=2, max_length=50),
        ),
    ]
