# Generated by Django 4.2.4 on 2023-08-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0013_shopcls_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutcls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ab_title', models.CharField(max_length=100)),
                ('ab_pic', models.ImageField(upload_to='imgs6')),
                ('ab_desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='blogcls',
            name='blog_pic',
            field=models.ImageField(upload_to='imgs3'),
        ),
        migrations.AlterField(
            model_name='officecls',
            name='off_pic',
            field=models.ImageField(upload_to='imgs4'),
        ),
        migrations.AlterField(
            model_name='servicescls',
            name='serv_pic',
            field=models.ImageField(upload_to='imgs5'),
        ),
        migrations.AlterField(
            model_name='shopcls',
            name='icone',
            field=models.ImageField(upload_to='imgs2'),
        ),
        migrations.AlterField(
            model_name='shopcls',
            name='picture',
            field=models.ImageField(upload_to='imgs1'),
        ),
    ]
