# Generated by Django 4.2.4 on 2023-09-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0014_aboutcls_alter_blogcls_blog_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeimgcls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_pic', models.ImageField(upload_to='imghome', verbose_name='عکس های خانه')),
                ('cat_home', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='aboutcls',
            name='ab_desc',
            field=models.TextField(verbose_name='توضیحات درباره ما'),
        ),
        migrations.AlterField(
            model_name='aboutcls',
            name='ab_pic',
            field=models.ImageField(upload_to='imgs6', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='aboutcls',
            name='ab_title',
            field=models.CharField(max_length=100, verbose_name='عنوان درباره ما'),
        ),
        migrations.AlterField(
            model_name='blogcls',
            name='blog_desc',
            field=models.CharField(max_length=1000, verbose_name='توضیحات خبر'),
        ),
        migrations.AlterField(
            model_name='blogcls',
            name='blog_pic',
            field=models.ImageField(upload_to='imgs3', verbose_name='عکس خبر'),
        ),
        migrations.AlterField(
            model_name='blogcls',
            name='blog_title',
            field=models.CharField(max_length=100, verbose_name='عنوان خبر'),
        ),
        migrations.AlterField(
            model_name='contactcls',
            name='email',
            field=models.CharField(max_length=50, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactcls',
            name='message',
            field=models.CharField(max_length=500, verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='contactcls',
            name='name',
            field=models.CharField(max_length=40, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='contactcls',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='officecls',
            name='off_name',
            field=models.CharField(max_length=50, verbose_name='نام ادراه'),
        ),
        migrations.AlterField(
            model_name='officecls',
            name='off_pic',
            field=models.ImageField(upload_to='imgs4', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='officecls',
            name='off_web',
            field=models.CharField(max_length=50, verbose_name='آدرس وب'),
        ),
        migrations.AlterField(
            model_name='servicescls',
            name='serv_desc',
            field=models.CharField(max_length=2000, verbose_name='توضیحات خدمات'),
        ),
        migrations.AlterField(
            model_name='servicescls',
            name='serv_name',
            field=models.CharField(max_length=50, verbose_name='نام خدمات'),
        ),
        migrations.AlterField(
            model_name='servicescls',
            name='serv_pic',
            field=models.ImageField(upload_to='imgs5', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='shopcls',
            name='address',
            field=models.CharField(max_length=300, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='shopcls',
            name='description',
            field=models.CharField(max_length=3000, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='shopcls',
            name='icone',
            field=models.ImageField(upload_to='imgs2', verbose_name='عکس صفحه فروشگاه ها'),
        ),
        migrations.AlterField(
            model_name='shopcls',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام مغازه'),
        ),
        migrations.AlterField(
            model_name='shopcls',
            name='phase',
            field=models.IntegerField(default=2, verbose_name='کتگری فاز'),
        ),
        migrations.AlterField(
            model_name='shopcls',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='shopcls',
            name='picture',
            field=models.ImageField(upload_to='imgs1', verbose_name=' عکس صفحه اطلاعات'),
        ),
        migrations.AlterField(
            model_name='shopcls',
            name='type_shop',
            field=models.CharField(max_length=50, verbose_name='نوع مغازه'),
        ),
    ]
