# Generated by Django 4.2.4 on 2023-09-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0015_homeimgcls_alter_aboutcls_ab_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeimgcls',
            name='cat_home',
        ),
        migrations.RemoveField(
            model_name='homeimgcls',
            name='home_pic',
        ),
        migrations.AddField(
            model_name='homeimgcls',
            name='home_pic1',
            field=models.ImageField(default=1, upload_to='imghome', verbose_name='1عکس خانه'),
        ),
        migrations.AddField(
            model_name='homeimgcls',
            name='home_pic2',
            field=models.ImageField(default=1, upload_to='imghome', verbose_name='2عکس خانه'),
        ),
    ]
