# Generated by Django 4.2.4 on 2023-09-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0016_remove_homeimgcls_cat_home_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeimgcls',
            name='home_pic1',
        ),
        migrations.RemoveField(
            model_name='homeimgcls',
            name='home_pic2',
        ),
        migrations.AddField(
            model_name='homeimgcls',
            name='img1',
            field=models.ImageField(default=1, upload_to='imghome1'),
        ),
        migrations.AddField(
            model_name='homeimgcls',
            name='img2',
            field=models.ImageField(default=2, upload_to='imghome2'),
        ),
    ]
